name: Deploy to AWS

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    name: Deploy Frontend to S3 + CloudFront
    runs-on: ubuntu-latest
    # Only run if PR was actually merged (not just closed)
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          
      - name: Upload to S3
        run: |
          echo "📤 Uploading frontend files to S3..."

          # Upload main files
          aws s3 cp index.html s3://retatrutide-frontend-372208783486/ \
            --region eu-west-1
          aws s3 cp manifest.json s3://retatrutide-frontend-372208783486/ \
            --region eu-west-1
          aws s3 cp robots.txt s3://retatrutide-frontend-372208783486/ \
            --region eu-west-1

          # Sync js directory
          aws s3 sync js/ s3://retatrutide-frontend-372208783486/js/ \
            --region eu-west-1 \
            --delete

          echo "✅ Upload complete (index.html, manifest.json, robots.txt, js/)"
          
      - name: Invalidate CloudFront cache
        run: |
          echo "🔄 Invalidating CloudFront cache..."
          INVALIDATION_ID=$(aws cloudfront create-invalidation \
            --distribution-id E2ZD0ACBBK8F5K \
            --paths "/*" \
            --query 'Invalidation.Id' \
            --output text)
          echo "✅ Invalidation started: $INVALIDATION_ID"
          echo "invalidation_id=$INVALIDATION_ID" >> $GITHUB_OUTPUT
        id: invalidate
        
      - name: Wait for cache invalidation
        run: |
          echo "⏳ Waiting for cache invalidation to complete..."
          echo "This usually takes 2-5 minutes"
          aws cloudfront wait invalidation-completed \
            --distribution-id E2ZD0ACBBK8F5K \
            --id ${{ steps.invalidate.outputs.invalidation_id }}
          echo "✅ Cache invalidation complete"
          
      - name: Deployment summary
        run: |
          echo "🎉 Deployment successful!"
          echo ""
          echo "Your app is now live at:"
          echo "https://d13m7vzwjqe4pp.cloudfront.net"
          echo ""
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Triggered by: ${{ github.actor }}"
